In [3]:
import numpy as np

In [11]:
v = np.random.randn(3, 1)
u = v/np.linalg.norm(v)
u

array([[-0.34016975],
       [-0.24753145],
       [ 0.90720049]])

In [31]:
V = np.random.randn(30, 3, 1)
U = np.zeros((30, 3, 1))
for i in range(len(V)):
  U[i] = V[i]/np.linalg.norm(V[i])

# Check if the for loop created unit vectors
for i in range(len(U)):
  print(np.linalg.norm(U[i]))

1.0
1.0
0.9999999999999999
0.9999999999999999
1.0
0.9999999999999999
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.9999999999999999
1.0000000000000002
1.0
1.0
1.0
0.9999999999999999
0.9999999999999999
1.0
0.9999999999999999
0.9999999999999998
0.9999999999999999
1.0
0.9999999999999999
1.0
1.0


In [32]:
u_dot_U = np.dot(np.transpose(u), U)
u_dot_U

array([[[ 0.17472826],
        [-0.45392364],
        [-0.57654814],
        [-0.98245107],
        [ 0.36600038],
        [ 0.80647962],
        [ 0.68861378],
        [ 0.46130443],
        [ 0.48915664],
        [-0.41137632],
        [-0.00599313],
        [-0.34724395],
        [ 0.83042279],
        [-0.15532566],
        [ 0.75326272],
        [ 0.62047763],
        [-0.89955945],
        [ 0.64664274],
        [ 0.25060092],
        [-0.71880761],
        [ 0.1417066 ],
        [-0.45088402],
        [ 0.07403393],
        [ 0.05922392],
        [ 0.98157264],
        [-0.07110064],
        [ 0.70412798],
        [-0.04993913],
        [-0.53493403],
        [ 0.32961596]]])

In [28]:
u_dot_U = u_dot_U.flatten()
u_dot_U

array([ 3.57263069e-01, -9.33262223e-01,  8.07239595e-01, -5.47935275e-01,
       -8.86580806e-02, -5.14023323e-01,  9.90747571e-01,  8.71438307e-01,
        7.44573091e-01,  5.20223532e-01, -8.54694493e-01,  2.61103536e-01,
        8.56359005e-01, -9.32118133e-01,  5.40004449e-02,  9.07192007e-01,
       -4.88679091e-01,  5.03577595e-01,  6.70058056e-01,  8.43791871e-01,
       -3.40005384e-01, -2.74854349e-01,  8.66021595e-01,  5.86760543e-02,
       -3.02687798e-04, -3.07988305e-01,  2.52395752e-01, -1.79812721e-01,
        2.42355224e-01,  4.89886476e-01])

In [26]:
np.mean(u_dot_U)

0.1611522905893919

In [29]:
np.var(u_dot_U)

0.34412728773782864